//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalevPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRole
    {
        public int EventRoleID { get; set; }
        public int EventID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Enent Enent { get; set; }
        public virtual Role Role { get; set; }
    }
}
